Parallel training via `do concurrent`
BerkeleyLab/inference-engine pull request #202
Opened 2024-09-03 23:36 UTC by rouson

2024-09-13 21:00 UTC, bonachea requested changes

2024-09-13 21:00 UTC, bonachea commented on src/inference_engine/trainable_engine_s.F90
> +#endif
Need to validate operation of locality specifiers on Cray and Intel

2024-09-13 21:05 UTC, bonachea requested changes
Probably also need to update the status of `do concurrent` support and usage in the top-level README

2024-09-14 00:31 UTC, rouson commented on src/inference_engine/trainable_engine_s.F90
> +#endif
@bonachea It took forever to find the Cray Fortran Reference Manual for the latest compiler version (18.0.0).  Once I found it, I didn't see any evidence of support for `reduce` locality so I'll remove the `defined(_CRAYFTN)` clause.

2024-09-14 01:33 UTC, rouson commented
@bonachea I think all the changes we've discussed have been made so I'll merge this.

2024-09-14 02:53 UTC, merged