Support building cloud-microphysics with LLVM Flang
BerkeleyLab/inference-engine pull request #203
Opened 2024-09-05 23:28 UTC by ktras

2024-09-06 00:04 UTC, rouson requested changes

2024-09-06 00:04 UTC, rouson commented on cloud-microphysics/setup.sh
> +elif [ $FPM_FC = "flang-new" ]; then
Let's handle the case when. `FPM_FC` contains the full path

2024-09-06 01:08 UTC, ktras commented on cloud-microphysics/setup.sh
> +elif [ $FPM_FC = "flang-new" ]; then
Great point! I have addressed this in the latest commit.

2024-09-07 02:04 UTC, rouson approved these changes
LGTM @ktras thanks for updating this!

2024-09-07 02:05 UTC, merged